In [72]:
import pandas
import json

In [73]:
df = pandas.read_parquet("media/elus-conseiller-darrondissement-ca.parquet")

In [74]:
df.head(2)

,code_du_departement,libelle_du_departement,code_de_la_commune,libelle_de_la_commune,libelle_du_secteur,nom_de_lelu,prenom_de_lelu,code_sexe,date_de_naissance,code_de_la_categorie_socio_professionnelle,libelle_de_la_categorie_socio_professionnelle,date_de_debut_du_mandat,libelle_de_la_fonction,date_de_debut_de_la_fonction,age,duree_du_mandat
0,13,Bouches-Du-Rhône,13055,Marseille,Marseille Secteur 1,AMICO,Patrick,M,1955-08-25,74,Ancien cadre,2026-03-22,NaN,NaN,71,0
1,13,Bouches-Du-Rhône,13055,Marseille,Marseille Secteur 1,BOURNEUF,Aurelien,M,2000-04-18,56,Personnel des services directs aux particuliers,2026-04-05,NaN,NaN,26,0

In [75]:
df[~df['age'].isna()]['age'].mean()

np.float64(47.876338851022396)

In [76]:
pandas.to_datetime(df.date_de_naissance).dt.month

0        8
1        4
2        6
3        3
4        3
        ..
1022    10
1023     4
1024     7
1025    12
1026    12
Name: date_de_naissance, Length: 1027, dtype: int32

In [91]:
firstname = 'Karim'
lastname = 'lali'

df['_firstname'] = False
df['_lastname'] = False

for item in df.itertuples():
    if firstname is not None:
        str_firstname = df.loc[item.Index, 'prenom_de_lelu']

        if firstname in str_firstname:
            df.loc[item.Index, '_firstname'] = True

    if lastname is not None:
        str_lastname = df.loc[item.Index, 'nom_de_lelu']
        
        if lastname in str_lastname:
            df.loc[item.Index, '_lastname'] = True

df[(df['_firstname'] == True) | (df['_lastname'] == True)]

,code_du_departement,libelle_du_departement,code_de_la_commune,libelle_de_la_commune,libelle_du_secteur,nom_de_lelu,prenom_de_lelu,code_sexe,date_de_naissance,code_de_la_categorie_socio_professionnelle,libelle_de_la_categorie_socio_professionnelle,date_de_debut_du_mandat,libelle_de_la_fonction,date_de_debut_de_la_fonction,age,duree_du_mandat,_firstname,_lastname
2,13,Bouches-Du-Rhône,13055,Marseille,Marseille Secteur 1,BOUSSALEM,Karim,M,1986-06-11,22,Commerçant et assimilé,2026-03-22,5ème adjoint au maire d'arrondissement,2026-04-05,40,0,True,False
156,13,Bouches-Du-Rhône,13055,Marseille,Marseille Secteur 5,LALI,Karim,M,1976-05-22,23,Chef d'entreprise de 10 salariés ou plus,2026-03-22,NaN,NaN,50,0,True,False
262,13,Bouches-Du-Rhône,13055,Marseille,Marseille Secteur 7,TOUCHE,Karim,M,1976-10-12,37,Cadre administratif et commercial d'entreprise,2026-03-22,NaN,NaN,50,0,True,False
280,13,Bouches-Du-Rhône,13055,Marseille,Marseille Secteur 8,DJEBALI,Karim,M,1982-09-25,43,Profession intermédiaire de la santé et du tra...,2026-03-22,3ème adjoint au maire d'arrondissement,2026-04-05,44,0,True,False
816,75,Paris,75056,Paris,Paris 17Eme Secteur,ZIADY,Karim,M,1989-05-09,34,"Professeur, profession scientifique",2026-03-22,NaN,NaN,37,0,True,False