In [33]:
import pandas
import pathlib

In [34]:
# https://www.data.gouv.fr/datasets/annuaire-des-avocats-de-france?resource_id=99c8ff76-c0ff-4046-80d7-c10fc8e51c34
path = pathlib.Path('../data/lawyers.parquet')
df = pandas.read_parquet(path)

In [35]:
df.head(2)

,civilit,acSalarie,Barreau,BarreauId,avCnbfCode,avLANG,avNom,avPrenom,avBarEntree,cbAdresse1,...,acdateentree,avMelOrdre,spLibelle1,spLibelle2,spLibelle3,acDateSerment,avDateExer,avInscription,,.1
0,F,False,AGEN,0002,300730,Français,AZZOUZ,Dahab,2019-01-01,28 rue Montesquieu,...,2025-07-01,dahab.azzouz@avocat.fr,NaN,NaN,NaN,None,20190101,1.0,NaN,NaN
1,F,False,AGEN,0002,300281,Français,BADY,Aurélia,2021-09-01,58 rue Mirabeau,...,2023-08-08,contact@bady-avocat.fr,NaN,NaN,NaN,None,20190102,1.0,NaN,NaN

In [36]:
df.Barreau.count()

np.int64(80956)

In [37]:
df.rename(columns={
    'civilit': 'civilite',
    'acSalarie': 'actif_salarie',
    'Barreau': 'barreau',
    'BarreauId': 'barreau_id',
    'avCnbfCode': 'av_cnbf_code',
    'avLANG': 'av_lang',
    'avNom': 'nom',
    'avPrenom': 'prenom',
    'avBarEntree': 'av_bar_entree',
    'cbAdresse1': 'cb_adresse_1',
    'cbAdresse2': 'cb_adresse_2',
    'cbCp': 'cb_cp',
    'cbVille': 'cb_ville',
    'cbTel': 'cb_tel',
    'cbFax': 'cb_fax',
    'cbSiretSiren': 'cb_siret_siren',
    'cbSiretNic': 'cb_siret_nic',
    'cbRaisonSociale': 'cb_raison_sociale',
    'acDateEntree': 'ac_date_entree',
    'cbFormJuri': 'cb_form_juri',
    'avMelOrdre': 'av_mel_ordre',
    'spLibelle1': 'sp_libelle_1',
    'spLibelle2': 'sp_libelle_2',
    'spLibelle3': 'sp_libelle_3',
    'acDateSerment': 'ac_date_serment',
    'avDateExer': 'av_date_exer',
    'avInscription': 'av_inscription',
    ' ': 'autre',
    ' .1': 'autre_1'
}, inplace=True)

In [38]:
df = df[['civilite', 'actif_salarie', 'barreau', 'barreau_id', 'av_cnbf_code', 'av_lang', 'nom', 'prenom', 'av_bar_entree', 'cb_adresse_1', 'cb_adresse_2', 'cb_cp', 'cb_ville', 'cb_tel', 'cb_fax', 'cb_siret_siren', 'cb_siret_nic', 'cb_raison_sociale', 'ac_date_entree', 'cb_form_juri', 'av_mel_ordre', 'sp_libelle_1', 'sp_libelle_2', 'sp_libelle_3', 'ac_date_serment', 'av_date_exer', 'av_inscription']]

In [39]:
df.head()

,civilite,actif_salarie,barreau,barreau_id,av_cnbf_code,av_lang,nom,prenom,av_bar_entree,cb_adresse_1,...,cb_raison_sociale,ac_date_entree,cb_form_juri,av_mel_ordre,sp_libelle_1,sp_libelle_2,sp_libelle_3,ac_date_serment,av_date_exer,av_inscription
0,F,False,AGEN,0002,300730,Français,AZZOUZ,Dahab,2019-01-01,28 rue Montesquieu,...,AZZOUZ DAHAB,2025-07-01,CABI,dahab.azzouz@avocat.fr,NaN,NaN,NaN,None,20190101,1.0
1,F,False,AGEN,0002,300281,Français,BADY,Aurélia,2021-09-01,58 rue Mirabeau,...,BADY AURÉLIA,2023-08-08,CABI,contact@bady-avocat.fr,NaN,NaN,NaN,None,20190102,1.0
2,F,False,AGEN,0002,081221,Français,BELACEL,Virginie,2011-01-01,103 avenue Jean Jaurès,...,VALAY-BELACEL-DELBREL-CERDAN,2006-01-01,SARL,v.belacel@avocats-vbd.com,NaN,NaN,NaN,None,20040202,1.0
3,M,False,AGEN,0002,051043,Français,BELLANDI,Philippe,1999-01-25,51 rue Albert-Camus,...,BELLANDI,1999-01-25,CABI,avocat@cabinet-pbellandi.fr,NaN,NaN,NaN,None,19990125,1.0
4,M,False,AGEN,0002,096606,Français,BERT,Guillaume,2021-07-01,5 rue des Ambans,...,BERT AVOCAT,2025-02-01,SARL,gb@bertavocat.fr,NaN,NaN,NaN,None,20120110,1.0

In [40]:
df.to_parquet(pathlib.Path('../data/lawyers-cleaned.parquet'), index=False)

In [45]:
df[df['barreau'] == 'AJACCIO']

,civilite,actif_salarie,barreau,barreau_id,av_cnbf_code,av_lang,nom,prenom,av_bar_entree,cb_adresse_1,...,cb_raison_sociale,ac_date_entree,cb_form_juri,av_mel_ordre,sp_libelle_1,sp_libelle_2,sp_libelle_3,ac_date_serment,av_date_exer,av_inscription
839,F,False,AJACCIO,0004,087627,Français,TIBERI,Julia,2009-03-10,4 Boulevard Masseria,...,TIBERI JULIA,2020-08-08,CABI,jt@btb-avocats.com,NaN,NaN,NaN,None,20090310,1.0
1070,M,None,AJACCIO,0004,V1.8,0,20260717,142\n,None,NaN,...,NaN,None,NaN,NaN,NaN,NaN,NaN,None,0,NaN
1071,F,False,AJACCIO,0004,076337,Français,ACQUAVIVA,Virginie,2012-11-05,9 Cours Jean Nicoli,...,ACQUAVIVA VIRGINIE,2020-04-06,CABI,acquaviva.v@hotmail.fr,NaN,NaN,NaN,None,20121105,1.0
1072,F,False,AJACCIO,0004,310005,Français,AIEVOLA,Barbara,2024-02-15,Espace Poretta,...,AIEVOLA BARBARA,2025-09-11,CABI,baievola-avocat@outlook.fr,NaN,NaN,NaN,None,20240215,1.0
1073,F,False,AJACCIO,0004,301514,Français,ANDARELLI,Carole,2019-02-11,LES CANDILELLI,...,ANDARELLI CAROLE,2019-02-11,CABI,andarelli.avocat@gmail.com,NaN,NaN,NaN,None,20190211,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,F,False,AJACCIO,0004,303047,Français,VAILLIER,Amanda,2020-01-27,62 Cours Napoléon,...,LIBERTAE-JURIS AVOCATS,2023-05-03,SARL,amanda.vaillier@avocat.fr,NaN,NaN,NaN,None,20200127,1.0
1208,M,False,AJACCIO,0004,096932,Français,VESPERINI,Jean François,2012-01-30,4 Cours Grandval,...,VESPERINI,2025-06-12,CABI,jfvesperini.avocat@gmail.com,NaN,NaN,NaN,None,20120130,1.0
1209,M,False,AJACCIO,0004,080467,Français,VINIER ORSETTI,Antoine,2004-01-19,65,...,VINIER ORSETTI ANTOINE,2025-02-11,CABI,me.vinierorsetti@orange.fr,NaN,NaN,NaN,None,20040119,1.0
1210,F,False,AJACCIO,0004,109600,Français,WITZ-SANTONI,Laura,2023-02-13,17 Cours Général Leclerc,...,WITZ-SANTONI LAURA,2024-01-11,CABI,lw@saj-avocats.fr,NaN,NaN,NaN,None,20180116,1.0
1211,F,False,AJACCIO,0004,098991,Français,ZILLER,Laetizia,2017-03-09,19 Avenue Beverini Vico,...,ZILLER LAETIZIA,2025-03-21,CABI,laetizia.ziller.avocat@gmail.com,NaN,NaN,NaN,None,20130304,1.0